/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseFileInput: typeof import('./src/components/Base/BaseFileInput.vue')['default']
    BaseInput: typeof import('./src/components/Base/BaseInput.vue')['default']
    BaselcAccept: typeof import('./src/components/Base/BaselcAccept.vue')['default']
    BaselcReserve: typeof import('./src/components/Base/BaselcReserve.vue')['default']
    BaseSelect: typeof import('./src/components/Base/BaseSelect.vue')['default']
    BaseSelectComponent: typeof import('./src/components/Base/BaseSelectComponent.vue')['default']
    BaseText: typeof import('./src/components/Base/BaseText.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GraphModeler: typeof import('./src/components/graph/GraphModeler.vue')['default']
    GraphModelerConfigBar: typeof import('./src/components/graph/GraphModelerConfigBar.vue')['default']
    GraphModelerElementsBar: typeof import('./src/components/graph/GraphModelerElementsBar.vue')['default']
    GraphModelerToolbar: typeof import('./src/components/graph/GraphModelerToolbar.vue')['default']
    GraphValidationErrors: typeof import('./src/components/graph/GraphValidationErrors.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
